# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-File-FixedRecLen
version:      0.4
version_from: lib/Tie/File/FixedRecLen.pm
installdirs:  site
requires:
    'Tie::File':      '= 0.97'

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
